name: tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
  pull_request_review:
    branches:
      - master
jobs:
  # refer to https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
  run_junit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      - name: Restore gradle.properties
        env:
          GP: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "${GP}" > ~/.gradle/gradle.properties

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run the Gradle build task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :build --scan